### ISSUE TITLE
Add assert_matches

### ISSUE THREAD

**Issue by Ollub** [qweeze/matchlib#1]
Is it possible to add comparison function like matches but where objects (on every level) will be compared in the assert statements. It will be helpful for testing, especially for comparing large structures.

**Comment by qweeze** [comment]
Sure, nice idea! 

It requires some rewriting though since we'd need to pass some metadata to every recursive call to `matches` that would preserve information about mismatched elements as well as current path in a structure. I don't have much time for adding it right now, but of course a contribution is welcomed

As a limited workaround, assuming you're using pytest:
```python
class MatchDict(dict):
    def __eq__(self, other):
        return matches(other, self)

def test_example():
    assert MatchDict({'key': 'val1'}) == {'key': 'val2'}
```
produces:
```
E       AssertionError: assert {'key': 'val1'} == {'key': 'val2'}
E         Differing items:
E         {'key': 'val1'} != {'key': 'val2'}

```
